//login
POST http://{{host}}:{{port}}/webtable
Content-Type: application/jsonn
token:hcytoken

{
  "u": "ashare",
  "marks":"Data1",
  "permission":["permission.Data2.delete", "permission.Data2.update", "permission.Data2.find", "Data2permission"]

}

###

###




###
