//login
POST http://{{host}}:{{port}}/webtable
Content-Type: application/jsonn
token:hcytoken

{
  "u": "gtable",
  "table":"Book",
  "pagenum":1,
  "pagesize":6,
  "sort":{
     "field":"book_price"
  },
  "find":[

  {key: "book_id", value: "1002", compare: "less"}

  ],


}

###

###




###
