//login
POST http://{{host}}:{{port}}/webtable
Content-Type: application/jsonn
token:hcytoken

{
  "u": "gtable",
  "table":"Data1",
  "pagenum":0,
  "pagesize":2,
  "like":{
     "id":"452760"
  }
}

###

###




###
