//login
POST http://{{host}}:{{port}}/webtable
Content-Type: application/jsonn
token:hcytoken

{
  "u": "login",
  "username": "admin",
  "passwd":"admin"
}

###

POST http://{{host}}:{{port}}/webtable
Content-Type: application/jsonn
token:hcytoken

{
  "u": "log1in",
  "passwd":"aaa"
}

###



